apiVersion: v1
kind: Secret
metadata:
# this is the jenkins id.
  name: gitlab-access-token
  namespace: jenkins
  labels:
# so we know what type it is.
    "jenkins.io/credentials-type": "secretText"
  annotations:
# description - can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "gitlab-access-token"
type: Opaque
stringData:
  text: glpat-xPtEwbs7NyD1pzeS-yKw