apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-cache-ci-pvc
  namespace: jenkins
spec:
  resources:
    requests:
      storage: 20Gi
  storageClassName: ceph-filesystem-ssd
  accessModes:
    - ReadWriteMany