apiVersion: v1
kind: Secret
metadata:
# this is the jenkins id.
  name: gitlab-http
  namespace: jenkins
  labels:
# so we know what type it is.
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
# description - can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "gitlab user http"
type: Opaque
stringData:
  username: jenkins-deploy
  password: zoqjIz-vigsy8-cygbam