apiVersion: v1
kind: Secret
metadata:
# this is the jenkins id.
  name: mysql-backup
  namespace: jenkins
  labels:
# so we know what type it is.
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
# description - can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "nexus creds for work with artifacts"
type: Opaque
stringData:
  username: backup_user
  password: Q8NbmR