---
- name: get charts path
  shell: pwd | sed s/ansible//
  register: charts_path

- name: Add chart repo tigera operator (networking)
  kubernetes.core.helm_repository:
    name: projectcalico
    repo_url: "https://docs.tigera.io/calico/charts"

- name: Deploy tigera operator (networking)
  kubernetes.core.helm:
    name: calico
    chart_ref: projectcalico/tigera-operator 
    release_namespace: tigera-operator
    create_namespace: true
    update_repo_cache: true
    values_files:
      - "{{ charts_path.stdout_lines[0] }}network-calico/values.yaml"


- name: Add chart repo metrics server
  kubernetes.core.helm_repository:
    name: metrics-server
    repo_url: "https://kubernetes-sigs.github.io/metrics-server/"

- name: Deploy metrics server
  kubernetes.core.helm:
    name: metrics-server
    chart_ref: metrics-server/metrics-server
    release_namespace: metrics-server
    create_namespace: true
    update_repo_cache: true
    values:
      replicas: 2
      args: 
        - --kubelet-insecure-tls


- name: Deploy nginx-ingress
  command: helm upgrade --install nginx-ingress oci://ghcr.io/nginxinc/charts/nginx-ingress -n nginx-ingress --create-namespace -f "{{ charts_path.stdout_lines[0] }}nginx-ingress/values.yaml"


- name: Add chart repo prometheus-grafana
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"

- name: Deploy prometheus-grafana
  kubernetes.core.helm:
    name: monitoring
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: monitoring
    create_namespace: true
    wait: true
    update_repo_cache: true
    values_files:
      - "{{ charts_path.stdout_lines[0] }}monitoring/prometheus-grafana/values.yaml"

- name: Add chart repo rook-ceph
  kubernetes.core.helm_repository:
    name: rook-release
    repo_url: "https://charts.rook.io/release"

- name: Deploy rook-ceph operator
  kubernetes.core.helm:
    name: rook-ceph
    chart_ref: rook-release/rook-ceph
    release_namespace: rook-ceph
    create_namespace: true
    wait: true
    update_repo_cache: true
    values_files:
      - "{{ charts_path.stdout_lines[0] }}rook-ceph/ceph-operator-values.yaml"
  
- name: Deploy custom ssd pools
  shell: | 
    kubectl apply -f "{{ charts_path.stdout_lines[0] }}rook-ceph/custom-mgr-ssd-pool.yaml"

- name: Pause for 5 minutes to create ceph cluster
  ansible.builtin.pause:
    minutes: 2

- name: Deploy rook-ceph-cluster
  kubernetes.core.helm:
    name: rook-ceph-cluster
    chart_ref: rook-release/rook-ceph-cluster
    release_namespace: rook-ceph
    create_namespace: true
    wait: true
    update_repo_cache: true
    values_files:
      - "{{ charts_path.stdout_lines[0] }}rook-ceph/ceph-cluster-values.yaml"

- name: Pause for 5 minutes to create ceph cluster
  ansible.builtin.pause:
    minutes: 5

- name: add tls cert for s3
  command: kubectl apply -f "{{ charts_path.stdout_lines[0] }}rook-ceph/wildcart-idcollect-ru-tls.yaml"

# - name: Deploy custom ssd pools
#   shell: | 
#     kubectl apply -f "{{ charts_path.stdout_lines[0] }}rook-ceph/custom-mgr-ssd-pool.yaml"
#     kubectl apply -f "{{ charts_path.stdout_lines[0] }}rook-ceph/custom-rgw-root-pool.yaml"

- name: add monitoring settings and buckets
  command: kubectl create -f "{{ charts_path.stdout_lines[0] }}monitoring/manifests-monitoring-settings/"