---

# - name: register kubectl config
#   shell: cat /etc/kubernetes/admin.conf
#   register: kubectl_config

# - name: print kubectl config
#   ansible.builtin.debug:
#     msg:  "{{ kubectl_config.stdout_lines }}"

# - name: Get content of remote file
#   ansible.builtin.slurp:
#     src: /etc/kubernetes/admin.conf
#   register: remote_file

# - name: Interpret remote file content as yaml
#   ansible.builtin.set_fact:
#     remote_yaml: '{{ remote_file.content | b64decode }}'

# - name: Print yaml for debugging purposes
#   ansible.builtin.debug:
#     var: remote_yaml


- name: register kubectl config
  command: sed "s/192.168.55.64/192.168.55.73/g" /etc/kubernetes/admin.conf
  register: kubectl_config

- name: Copy kubectl configto local file
  become: false
  local_action: copy content="{{ kubectl_config.stdout }}" dest="./kubectl_config"