installation:
  cni:
    type: Calico
  calicoNetwork:
    bgp: Disabled
    ipPools:
    - cidr: 100.100.8.0/23
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()