---
- name: get certificate-key
  command: kubeadm init phase upload-certs --upload-certs
  register: certificate_key

- name: Generate join command
  command: kubeadm token create --print-join-command --certificate-key="{{ certificate_key.stdout_lines[2] }}"
  register: join_command

- name: Copy join command to local file
  become: false
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command-control-node"
  
