apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: loki-chunks-bucket
  namespace: monitoring
spec:
  generateBucketName: loki-chunks-bucket
  storageClassName: ceph-bucket